//go:generate go run github.com/swaggo/swag/cmd/swag@v1.16.4 init -g main.go -o docs/

package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/rayer/llm-wiki-bff/internal/auth"
	"github.com/rayer/llm-wiki-bff/internal/buildinfo"
	conceptcache "github.com/rayer/llm-wiki-bff/internal/cache"
	"github.com/rayer/llm-wiki-bff/internal/config"
	"github.com/rayer/llm-wiki-bff/internal/firestore"
	"github.com/rayer/llm-wiki-bff/internal/gcs"
	handlerv1 "github.com/rayer/llm-wiki-bff/internal/handler/v1"
	"github.com/rayer/llm-wiki-bff/internal/llm"
	"github.com/rayer/llm-wiki-bff/internal/localfs"
	"github.com/rayer/llm-wiki-bff/internal/middleware"
	"github.com/rayer/llm-wiki-bff/internal/observability"
	"github.com/rayer/llm-wiki-bff/internal/query"
	"github.com/rayer/llm-wiki-bff/internal/queryquality"
	"github.com/rayer/llm-wiki-bff/internal/search"
	store "github.com/rayer/llm-wiki-bff/internal/storage"
	"github.com/rayer/llm-wiki-bff/internal/syssettings"
	"github.com/rayer/llm-wiki-bff/internal/wikiindex"

	_ "github.com/rayer/llm-wiki-bff/docs" // swagger docs (generated by swag init)
)

//	@title			LLM Wiki BFF API
//	@version		1.0
//	@description	Backend-for-frontend API for the LLM Wiki project. Serves wiki sources and concepts with full-text search, import, and pipeline status.
//	@contact.name	LLM Wiki Team
//
//	@BasePath	/
//
//
//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
//	@description				JWT Bearer token from /api/v1/auth/login. Format: \"Bearer <token>\".
//
//	@securityDefinitions.apikey	DevUserAuth
//	@in							header
//	@name						X-User-ID
//	@description				DEV mode user identity header. Required when dev_jwt=true.
//
//	@securityDefinitions.apikey	ProjectHeader
//	@in							header
//	@name						X-Project-ID
//	@description				Project identifier header.

func main() {
	localFlag := flag.String("local", "", "local data directory")
	flag.Parse()

	cfg, err := config.Load(".")
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	localDataDir := strings.TrimSpace(*localFlag)
	if localDataDir == "" {
		localDataDir = strings.TrimSpace(cfg.LocalDataDir)
	}
	if localDataDir == "" {
		localDataDir = strings.TrimSpace(os.Getenv("LOCAL_DATA_DIR"))
	}
	localMode := localDataDir != ""

	var wikiStore store.RootStore
	if localMode {
		wikiStore = localfs.New(localDataDir)
		log.Printf("Local wiki storage ready: %s", localDataDir)
	} else {
		gcsClient, err := gcs.NewClient(cfg.Bucket)
		if err != nil {
			log.Fatalf("Failed to create GCS client: %v", err)
		}
		wikiStore = gcsClient
		log.Printf("GCS client ready: gs://%s/", cfg.Bucket)
	}

	// Init Firestore client
	var fsClient *firestore.Client
	if localMode {
		log.Printf("Local mode: Firestore client disabled")
	} else {
		fsClient, err = firestore.NewClientWithDatabase(cfg.GCPProject, cfg.FirestoreDatabaseID, "", "")
		if err != nil {
			log.Printf("WARNING: Firestore client not available: %v", err)
		} else {
			auth.CreateTestUser(context.Background(), fsClient.Raw())
		}
	}

	// Search metadata index
	idx := search.NewIndex()
	log.Printf("Search metadata index: not yet rebuilt — call /api/v1/pipeline/rebuild-index")
	log.Printf("Concept bodies: not yet rebuilt — call /api/v1/pipeline/rebuild-index")

	// Project-scoped concept cache for the V1 query path.
	conceptCache := conceptcache.New()
	log.Printf("Concept cache: not yet rebuilt — call /api/v1/pipeline/rebuild-index")

	productionExecutor, err := newProductionQueryExecutor(cfg, conceptCache)
	if err != nil {
		log.Fatalf("Failed to create production query executor: %v", err)
	}

	// OpenTelemetry metrics (graceful fallback)
	provider, err := observability.InitMetrics(context.Background(), observabilityServiceName(os.Getenv("K_SERVICE")), observability.GetProjectID())
	if err != nil {
		log.Printf("[observability] WARNING: metrics init failed (continuing): %v", err)
	} else {
		defer func() {
			if err := provider.Shutdown(context.Background()); err != nil {
				log.Printf("[observability] metrics shutdown error: %v", err)
			}
		}()
	}

	// Handlers
	hV1 := handlerv1.New(wikiStore, fsClient, idx, conceptCache, nil, nil)
	hV1.SetQueryExecutor(productionExecutor)
	hV1.SetPipelineJobURL(cfg.PipelineJobURL)
	hV1.SetPipelineQuotaConfig(
		cfg.PipelineDailyLimit,
		cfg.PipelineCooldownSeconds,
		cfg.PipelineMinNewRaw,
		cfg.PipelineDemoUserIDs,
	)
	if localMode {
		hV1.SetRebuildIndexFunc(func(ctx context.Context, userID, projectID string) (wikiindex.IDMap, error) {
			return handlerv1.RebuildIndexForStore(ctx, wikiStore.Scope(userID, projectID))
		})
	}

	// Gin router
	r := gin.Default()
	r.Use(middleware.SecurityHeaders(!cfg.DevJWT))

	// OpenTelemetry latency middleware (per-endpoint)
	r.Use(middleware.LatencyMiddleware())

	// CORS — must be BEFORE routes
	allowOrigins := cfg.AllowedOriginsFor(localMode)
	r.Use(cors.New(cors.Config{
		AllowOrigins:     allowOrigins,
		AllowMethods:     []string{"GET", "POST", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Content-Type", "Authorization", "X-User-ID", "X-User-Role", "X-Project-ID", "Idempotency-Key"},
		AllowCredentials: true,
	}))

	var settingsStore *syssettings.Store
	if !localMode && fsClient != nil && fsClient.Raw() != nil {
		settingsStore = syssettings.NewStore(fsClient.Raw(), cfg.RegistrationEnabled)
	} else {
		settingsStore = syssettings.NewStore(nil, cfg.RegistrationEnabled)
	}

	registerPublicRoutes(r, settingsStore)

	// Public auth routes (no auth middleware)
	authRoutes := r.Group("/api/v1/auth")
	{
		if localMode {
			authRoutes.POST("/login", middleware.NewRateLimiter(10, time.Minute), auth.LocalDevLoginHandler(cfg.JWTSecret))
			authRoutes.POST("/register", func(c *gin.Context) {
				c.JSON(http.StatusServiceUnavailable, gin.H{"error": "registration is disabled in local mode; use demo@llm-wiki.dev / demo123456"})
			})
			authRoutes.POST("/refresh", auth.LocalDevRefreshHandler(cfg.JWTSecret))
			authRoutes.POST("/logout", auth.LogoutHandler())
		} else if fsClient == nil || fsClient.Raw() == nil {
			unavailable := func(c *gin.Context) {
				c.JSON(http.StatusServiceUnavailable, gin.H{"error": "auth routes require Firestore"})
			}
			authRoutes.POST("/login", unavailable)
			authRoutes.POST("/register", unavailable)
			authRoutes.POST("/refresh", unavailable)
			authRoutes.POST("/logout", auth.LogoutHandler())
		} else {
			authRoutes.POST("/login", middleware.NewRateLimiter(10, time.Minute), auth.LoginHandler(fsClient.Raw(), cfg.JWTSecret))
			authRoutes.POST("/register", middleware.NewRateLimiter(5, time.Minute), auth.RegisterHandler(fsClient.Raw(), cfg.JWTSecret, settingsStore))
			authRoutes.POST("/refresh", auth.RefreshHandler(fsClient.Raw(), cfg.JWTSecret))
			authRoutes.POST("/logout", auth.LogoutHandler())
		}
	}

	// ── Swagger UI ──
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// ── API v1 (with JWT auth + project routing) ──
	v1 := r.Group("/api/v1")

	// Internal: pipeline worker calls this directly (no user JWT)
	v1.POST("/pipeline/rebuild-index", hV1.RebuildIndex)

	v1.Use(auth.JWTAuth(cfg))
	{
		v1.GET("/health", hV1.Health)
		v1.GET("/ready", hV1.Ready)
		v1.GET("/projects", hV1.ListProjects)
		v1.POST("/init-project", hV1.InitProject)
		v1.GET("/projects/:pid/status", hV1.ProjectStatus)
	}

	registerAdminRoutes(r, cfg, hV1, settingsStore)

	v1.Use(auth.ProjectMiddleware())
	{
		v1.GET("/index", hV1.Index)
		v1.POST("/query", hV1.Query)
		v1.GET("/sources", hV1.ListSources)
		v1.GET("/sources/:id/annotation", hV1.GetAnnotation)
		v1.PUT("/sources/:id/annotation", hV1.PutAnnotation)
		v1.GET("/sources/:id", hV1.GetSource)
		v1.GET("/concepts", hV1.ListConcepts)
		v1.GET("/concepts/:id", hV1.GetConcept)
		v1.POST("/import", hV1.Import)
		v1.POST("/pipeline/run", hV1.PipelineRun)
		v1.GET("/pipeline/status", hV1.PipelineStatus)
		v1.GET("/pipeline/log", hV1.PipelineLog)
		v1.GET("/raw", hV1.RawList)
		v1.GET("/raw/:filename", hV1.RawPreview)
		v1.POST("/raw/upload", hV1.RawUpload)
		v1.GET("/status", hV1.Status)
		v1.GET("/metrics", hV1.PrometheusMetrics)
	}

	// ── Static frontend ──
	r.StaticFile("/", "./static/index.html")
	r.Static("/static", "./static")
	r.NoRoute(func(c *gin.Context) {
		// SPA fallback: serve index.html for non-API routes
		if !strings.HasPrefix(c.Request.URL.Path, "/api") {
			c.File("./static/index.html")
		}
	})

	log.Printf("BFF listening on :%s", cfg.Port)
	log.Printf("Swagger UI: http://localhost:%s/swagger/index.html", cfg.Port)
	log.Fatal(r.Run(":" + cfg.Port))
}

func newProductionQueryExecutor(cfg config.Config, conceptCache *conceptcache.Cache) (query.Executor, error) {
	selectionLimit := cfg.QuerySelectionLimit
	if selectionLimit == 0 {
		selectionLimit = config.DefaultQuerySelectionLimit
	}
	explorationSlots := cfg.QuerySelectionExplorationSlots
	if cfg.QuerySelectionLimit == 0 && explorationSlots == 0 {
		explorationSlots = config.DefaultQuerySelectionExplorationSlots
	}
	evidenceThreshold := cfg.QuerySelectionEvidenceThreshold
	evidenceThresholdSet := cfg.QuerySelectionEvidenceThreshold != 0
	if evidenceThreshold == 0 {
		evidenceThreshold = config.DefaultQuerySelectionEvidenceThreshold
	}
	if cfg.QueryExpansionModel == "" {
		cfg.QueryExpansionModel = config.DefaultQueryExpansionModel
	}
	if cfg.AnswerSynthesisModel == "" {
		cfg.AnswerSynthesisModel = config.DefaultAnswerSynthesisModel
	}
	if cfg.AnswerSynthesisReasoning == "" {
		cfg.AnswerSynthesisReasoning = config.DefaultAnswerSynthesisReasoning
	}
	if cfg.QueryExpansionModel != "" && cfg.QueryExpansionModel != config.DefaultQueryExpansionModel {
		return nil, fmt.Errorf("query expansion model must be %s", config.DefaultQueryExpansionModel)
	}
	synthesisClient := llm.NewClientWithOptions(cfg.DeepSeekAPIKey, llm.ClientOptions{Model: cfg.AnswerSynthesisModel, Reasoning: cfg.AnswerSynthesisReasoning})
	if cfg.DeepSeekAPIKey != "" && synthesisClient == nil {
		return nil, errors.New("invalid answer synthesis client configuration")
	}
	temperature := 0.0
	expansionClient := llm.NewClientWithOptions(cfg.DeepSeekAPIKey, llm.ClientOptions{Model: cfg.QueryExpansionModel, Temperature: &temperature, Reasoning: config.DefaultQueryExpansionReasoning})
	var expansionProvider queryquality.ChatProvider
	if expansionClient != nil {
		expansionProvider = expansionClient
	}
	legacyExpander, err := llm.NewExpander(nil, "lifestyle")
	if err != nil {
		return nil, err
	}
	legacy := query.NewService(conceptCache, legacyExpander, synthesisClient)
	return queryquality.NewProductionExecutor(conceptCache, expansionProvider, legacy, legacy, queryquality.Options{
		SelectionLimit: selectionLimit, ExplorationSlots: explorationSlots,
		EvidenceThreshold: evidenceThreshold, EvidenceThresholdSet: evidenceThresholdSet,
		KeywordsPerAttempt:    cfg.QueryExpansionKeywordsPerAttempt,
		ExpansionAttempts:     cfg.QueryExpansionAttempts,
		RareDocumentFrequency: cfg.QueryMatchingRareKeywordMaxDocumentFrequency,
	})
}

func registerPublicRoutes(r *gin.Engine, settingsStore syssettings.RegistrationGate) {
	// Public routes are registered on the root router, outside JWT and project middleware.
	r.GET("/api/v1/public/config", syssettings.PublicConfigHandler(settingsStore))
	r.GET("/api/v1/public/version", buildinfo.Handler())
}

const legacyObservabilityServiceName = "llm-wiki-bff-dev"

func observabilityServiceName(kService string) string {
	if serviceName := strings.TrimSpace(kService); serviceName != "" {
		return serviceName
	}
	return legacyObservabilityServiceName
}

func registerAdminRoutes(r *gin.Engine, cfg config.Config, hV1 *handlerv1.Handler, settingsStore syssettings.RegistrationGate) {
	admin := r.Group("/api/v1/admin")
	admin.Use(auth.JWTAuth(cfg), auth.AdminOnly())
	{
		admin.GET("/settings", syssettings.AdminGetSettingsHandler(settingsStore))
		admin.PATCH("/settings", syssettings.AdminPatchSettingsHandler(settingsStore))
		admin.GET("/projects", hV1.AdminProjects)
		admin.PATCH("/projects/:id", hV1.AdminRenameProject)
		admin.DELETE("/projects/:id", hV1.AdminDeleteProject)
		admin.POST("/projects/:id/pipeline", hV1.AdminPipelineTrigger)
		admin.POST("/projects/:id/rebuild-index", hV1.AdminRebuildIndex)
		admin.GET("/users", hV1.AdminListUsers)
		admin.PATCH("/users/:id", hV1.AdminUpdateUser)
		admin.DELETE("/users/:id", hV1.AdminDeleteUser)
	}
}
