package firestore

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"cloud.google.com/go/firestore"
	"github.com/rayer/llm-wiki-bff/internal/pipelinequota"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

const (
	pipelineQuotaCollection            = "pipeline_quota"
	pipelineQuotaReservationCollection = "pipeline_quota_reservations"
)

// QuotaReservation ties one accepted user run to its quota debit. Its settlement
// fields are changed in the same transaction that applies a refund.
type QuotaReservation struct {
	ID                string
	UserID            string
	ProjectID         string
	ExecutionID       string
	ReservedAt        time.Time
	PreviousLastRunAt time.Time
	DayKey            string
	SettlementStatus  string
	Outcome           string
}

// QuotaDocID returns the pipeline_quota document ID for a user/project pair.
func QuotaDocID(userID, projectID string) string {
	return fmt.Sprintf("%s__%s", userID, projectID)
}

// LoadQuotaState reads the pipeline_quota document (missing → zeros).
func (c *Client) LoadQuotaState(ctx context.Context, userID, projectID string) (runsToday int, dayKey string, lastRunAt time.Time, err error) {
	doc, err := Collection(c.fs, pipelineQuotaCollection).Doc(QuotaDocID(userID, projectID)).Get(ctx)
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return 0, "", time.Time{}, nil
		}
		return 0, "", time.Time{}, err
	}
	runsToday, dayKey, lastRunAt = quotaStateFromData(doc.Data())
	return runsToday, dayKey, lastRunAt, nil
}

// ReserveQuota evaluates quota and creates the execution-owned reservation in
// one transaction. The reservation ID is generated by the accepting handler
// before this call and is also carried by the backend execution.
func (c *Client) ReserveQuota(
	ctx context.Context,
	reservationID, userID, projectID string,
	limits pipelinequota.Limits,
	now time.Time,
	isDemo, alreadyRunning bool,
	newRawFiles, rawDirtyFiles, annotationDirtyFiles int,
) (snap pipelinequota.Snapshot, reserved bool, err error) {
	reservationID = strings.TrimSpace(reservationID)
	if reservationID == "" || strings.ContainsAny(reservationID, "/\\") {
		return pipelinequota.Snapshot{}, false, errors.New("invalid pipeline quota reservation ID")
	}
	now = now.UTC().Truncate(time.Microsecond)
	quotaRef := Collection(c.fs, pipelineQuotaCollection).Doc(QuotaDocID(userID, projectID))
	reservationRef := Collection(c.fs, pipelineQuotaReservationCollection).Doc(reservationID)

	err = c.fs.RunTransaction(ctx, func(ctx context.Context, tx *firestore.Transaction) error {
		snap = pipelinequota.Snapshot{}
		reserved = false
		runsToday, dayKey, lastRunAt, readErr := readQuotaStateTx(tx, quotaRef)
		if readErr != nil {
			return readErr
		}
		lastRunAt = normalizeQuotaTime(lastRunAt)

		pre := pipelinequota.Evaluate(pipelinequota.Input{
			Now: now, Limits: limits, IsDemo: isDemo, AlreadyRunning: alreadyRunning,
			RunsToday: runsToday, DayKey: dayKey, LastRunAt: lastRunAt,
			NewRawFiles: newRawFiles, RawDirtyFiles: rawDirtyFiles,
			AnnotationDirtyFiles: annotationDirtyFiles, Enforced: true,
		})
		if !pre.Allowed {
			snap = pre
			return nil
		}

		today := pipelinequota.DayKeyUTC(now)
		newRuns := pre.RunsToday + 1
		if err := tx.Set(quotaRef, map[string]interface{}{
			"user_id": userID, "project_id": projectID, "day_key": today,
			"runs_today": newRuns, "last_run_at": now, "updated_at": now,
		}); err != nil {
			return err
		}
		if err := tx.Create(reservationRef, map[string]interface{}{
			"user_id": userID, "project_id": projectID,
			"reserved_at": now, "day_key": today,
			"previous_last_run_at": lastRunAt,
			"settlement_status":    "pending", "outcome": "",
			"execution_id": "", "created_at": now,
		}); err != nil {
			return err
		}

		snap = pipelinequota.Evaluate(pipelinequota.Input{
			Now: now, Limits: limits, IsDemo: isDemo, AlreadyRunning: alreadyRunning,
			RunsToday: newRuns, DayKey: today, LastRunAt: now,
			NewRawFiles: newRawFiles, RawDirtyFiles: rawDirtyFiles,
			AnnotationDirtyFiles: annotationDirtyFiles, Enforced: true,
		})
		reserved = true
		return nil
	})
	if err != nil {
		return pipelinequota.Snapshot{}, false, err
	}
	return snap, reserved, nil
}

// LinkQuotaReservation records the Cloud Run execution ID after the provider
// accepts the job. The reservation ID is also in the job environment so a
// reconciler can recover if this write is temporarily unavailable.
func (c *Client) LinkQuotaReservation(ctx context.Context, reservationID, executionID string) error {
	_, err := Collection(c.fs, pipelineQuotaReservationCollection).Doc(reservationID).Update(ctx, []firestore.Update{
		{Path: "execution_id", Value: executionID},
		{Path: "updated_at", Value: time.Now().UTC()},
	})
	return err
}

func (c *Client) GetQuotaReservation(ctx context.Context, reservationID string) (QuotaReservation, bool, error) {
	return GetQuotaReservationFromFirestore(ctx, c.fs, reservationID)
}

func GetQuotaReservationFromFirestore(ctx context.Context, fs *firestore.Client, reservationID string) (QuotaReservation, bool, error) {
	snapshot, err := Collection(fs, pipelineQuotaReservationCollection).Doc(reservationID).Get(ctx)
	if status.Code(err) == codes.NotFound {
		return QuotaReservation{}, false, nil
	}
	if err != nil {
		return QuotaReservation{}, false, err
	}
	return quotaReservationFromData(reservationID, snapshot.Data()), true, nil
}

func (c *Client) ListPendingQuotaReservations(ctx context.Context) ([]QuotaReservation, error) {
	return ListPendingQuotaReservationsFromFirestore(ctx, c.fs)
}

func ListPendingQuotaReservationsFromFirestore(ctx context.Context, fs *firestore.Client) ([]QuotaReservation, error) {
	docs, err := Collection(fs, pipelineQuotaReservationCollection).
		Where("settlement_status", "==", "pending").Documents(ctx).GetAll()
	if err != nil {
		return nil, err
	}
	reservations := make([]QuotaReservation, 0, len(docs))
	for _, doc := range docs {
		reservations = append(reservations, quotaReservationFromData(doc.Ref.ID, doc.Data()))
	}
	return reservations, nil
}

// SettleQuotaReservation applies a confirmed terminal result. Replays are
// idempotent because the reservation state and any refund share one transaction.
func (c *Client) SettleQuotaReservation(ctx context.Context, reservationID, executionStatus string) (string, error) {
	var settlement string
	err := c.fs.RunTransaction(ctx, func(ctx context.Context, tx *firestore.Transaction) error {
		var err error
		settlement, err = SettleQuotaReservationInTransaction(ctx, tx, c.fs, reservationID, executionStatus)
		return err
	})
	return settlement, err
}

// SettleQuotaReservationInTransaction lets the local execution writer commit
// terminal execution state and its quota settlement atomically.
func SettleQuotaReservationInTransaction(ctx context.Context, tx *firestore.Transaction, fs *firestore.Client, reservationID, executionStatus string) (string, error) {
	if strings.TrimSpace(reservationID) == "" {
		return "not_applicable", nil
	}
	reservationRef := Collection(fs, pipelineQuotaReservationCollection).Doc(reservationID)
	reservationSnapshot, err := tx.Get(reservationRef)
	if status.Code(err) == codes.NotFound {
		return "not_applicable", nil
	}
	if err != nil {
		return "", err
	}
	reservation := quotaReservationFromData(reservationID, reservationSnapshot.Data())
	if reservation.SettlementStatus != "pending" {
		return reservation.SettlementStatus, nil
	}

	switch strings.ToUpper(strings.TrimSpace(executionStatus)) {
	case "SUCCEEDED", "CANCELLED":
		settlement := "charged"
		if err := tx.Update(reservationRef, []firestore.Update{
			{Path: "settlement_status", Value: settlement},
			{Path: "outcome", Value: strings.ToUpper(strings.TrimSpace(executionStatus))},
			{Path: "settled_at", Value: time.Now().UTC()},
		}); err != nil {
			return "", err
		}
		return settlement, nil
	case "FAILED":
		quotaRef := Collection(fs, pipelineQuotaCollection).Doc(QuotaDocID(reservation.UserID, reservation.ProjectID))
		quotaSnapshot, err := tx.Get(quotaRef)
		if err != nil {
			return "", err
		}
		data := quotaSnapshot.Data()
		runsToday, dayKey, lastRunAt := quotaStateFromData(data)
		updates := make([]firestore.Update, 0, 2)
		if dayKey == reservation.DayKey && runsToday > 0 {
			updates = append(updates, firestore.Update{Path: "runs_today", Value: runsToday - 1})
		}
		if sameQuotaTime(lastRunAt, reservation.ReservedAt) {
			if reservation.PreviousLastRunAt.IsZero() {
				updates = append(updates, firestore.Update{Path: "last_run_at", Value: firestore.Delete})
			} else {
				updates = append(updates, firestore.Update{Path: "last_run_at", Value: reservation.PreviousLastRunAt})
			}
		}
		if len(updates) > 0 {
			updates = append(updates, firestore.Update{Path: "updated_at", Value: time.Now().UTC()})
			if err := tx.Update(quotaRef, updates); err != nil {
				return "", err
			}
		}
		if err := tx.Update(reservationRef, []firestore.Update{
			{Path: "settlement_status", Value: "refunded"},
			{Path: "outcome", Value: "FAILED"},
			{Path: "settled_at", Value: time.Now().UTC()},
		}); err != nil {
			return "", err
		}
		return "refunded", nil
	default:
		return "pending", nil
	}
}

func quotaReservationFromData(id string, data map[string]interface{}) QuotaReservation {
	reservation := QuotaReservation{ID: id, SettlementStatus: "pending"}
	reservation.UserID, _ = data["user_id"].(string)
	reservation.ProjectID, _ = data["project_id"].(string)
	reservation.ExecutionID, _ = data["execution_id"].(string)
	reservation.DayKey, _ = data["day_key"].(string)
	reservation.SettlementStatus, _ = data["settlement_status"].(string)
	reservation.Outcome, _ = data["outcome"].(string)
	if t, ok := firestoreTimestamp(data["reserved_at"]); ok {
		reservation.ReservedAt = normalizeQuotaTime(t)
	}
	if t, ok := firestoreTimestamp(data["previous_last_run_at"]); ok {
		reservation.PreviousLastRunAt = normalizeQuotaTime(t)
	}
	return reservation
}

func sameQuotaTime(a, b time.Time) bool {
	return !a.IsZero() && !b.IsZero() && normalizeQuotaTime(a).Equal(normalizeQuotaTime(b))
}

func normalizeQuotaTime(t time.Time) time.Time {
	if t.IsZero() {
		return time.Time{}
	}
	return t.UTC().Truncate(time.Microsecond)
}

func readQuotaStateTx(tx *firestore.Transaction, ref *firestore.DocumentRef) (runsToday int, dayKey string, lastRunAt time.Time, err error) {
	snap, err := tx.Get(ref)
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return 0, "", time.Time{}, nil
		}
		return 0, "", time.Time{}, err
	}
	runsToday, dayKey, lastRunAt = quotaStateFromData(snap.Data())
	return runsToday, dayKey, lastRunAt, nil
}

// quotaStateFromData extracts quota fields from a pipeline_quota document.
func quotaStateFromData(data map[string]interface{}) (runsToday int, dayKey string, lastRunAt time.Time) {
	if data == nil {
		return 0, "", time.Time{}
	}
	runsToday = intFromFirestore(data["runs_today"])
	if v, ok := data["day_key"].(string); ok {
		dayKey = v
	}
	if t, ok := firestoreTimestamp(data["last_run_at"]); ok {
		lastRunAt = t
	}
	return runsToday, dayKey, lastRunAt
}

func intFromFirestore(v interface{}) int {
	switch n := v.(type) {
	case int:
		return n
	case int32:
		return int(n)
	case int64:
		return int(n)
	case float64:
		return int(n)
	case float32:
		return int(n)
	default:
		return 0
	}
}
