// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "LLM Wiki Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/projects": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all projects from Firestore. Supports optional ?user_id query filter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all projects (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/projects/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a project: removes GCS data, Firestore project doc, and lock doc.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Delete a project (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project doc ID ({userID}_{projectID})",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the name field on a Firestore project document.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Rename a project (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project doc ID ({userID}_{projectID})",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New project name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/projects/{id}/pipeline": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invokes the Cloud Run worker job for the specified project, then rebuilds the search index.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Trigger pipeline + rebuild for a project (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project doc ID ({userID}_{projectID})",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/projects/{id}/rebuild-index": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Triggers an index rebuild for the specified project using GCS-scoped data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Rebuild index for a project (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project doc ID ({userID}_{projectID})",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/settings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get system settings (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/syssettings.Settings"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update system settings (admin)",
                "parameters": [
                    {
                        "description": "Settings payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/syssettings.patchSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/syssettings.Settings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all users from Firestore. Supports optional ?role=admin query filter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all users (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by role (e.g. admin)",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a user and all their projects (GCS data + Firestore docs + locks).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Delete a user (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a user's role in Firestore.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update a user (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New role (e.g. admin)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "role": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates email and password, returns a 15-minute access token, and sets a seven-day refresh_token cookie. In local mode, the cookie omits Domain and Secure.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        },
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "Firestore mode: refresh_token; Path=/; Domain=rayer.idv.tw; Max-Age=604800; HttpOnly; Secure; SameSite=Lax"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/auth.RateLimitErrorResponse"
                        },
                        "headers": {
                            "Retry-After": {
                                "type": "integer",
                                "description": "Seconds until the rate limit window resets"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Clears the refresh_token cookie. No access token or request body is required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LogoutResponse"
                        },
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "refresh_token; Path=/; Domain=rayer.idv.tw; Max-Age=0; HttpOnly; Secure; SameSite=Lax"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Requires the refresh_token cookie. The cookie is single-use and is rotated on success; the response returns a new 15-minute access token and seven-day refresh_token cookie. In local mode, the cookie omits Domain and Secure.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh an access token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "refresh_token=\u003ctoken\u003e",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshResponse"
                        },
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "Firestore mode: refresh_token; Path=/; Domain=rayer.idv.tw; Max-Age=604800; HttpOnly; Secure; SameSite=Lax"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Returns a JWT in the response body and does not set a refresh cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register an account",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/auth.RateLimitErrorResponse"
                        },
                        "headers": {
                            "Retry-After": {
                                "type": "integer",
                                "description": "Seconds until the rate limit window resets"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/concepts": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns published wiki concepts by default. Set include_drafts=true to include draft concepts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "concepts"
                ],
                "summary": "List wiki concepts",
                "parameters": [
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Include draft concepts",
                        "name": "include_drafts",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ConceptsListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/concepts/{slug}": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns full content (frontmatter + body) for a wiki concept.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "concepts"
                ],
                "summary": "Get a concept by slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Concept slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ConceptDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns the V1 API health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/import": {
            "post": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Accepts a list of URLs to import (Phase 2 — placeholder).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "import"
                ],
                "summary": "Import bookmarks",
                "parameters": [
                    {
                        "description": "URLs to import",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ImportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ImportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/index": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns the cached ID map JSON for the request scope.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "index"
                ],
                "summary": "Read generated index",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics": {
            "get": {
                "security": [
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns scoped wiki statistics in Prometheus exposition format.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Prometheus metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/pipeline/log": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns the stdout and stderr log captured by the pipeline worker for the current project execution.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "pipeline"
                ],
                "summary": "Read pipeline log",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cloud Run execution ID",
                        "name": "execution_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/pipeline/status": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns the latest Cloud Run pipeline execution for the current project. Pass execution_id to fetch a specific execution. When an execution is available, last_execution.log_url points to the authenticated log endpoint.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline"
                ],
                "summary": "Pipeline execution status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cloud Run execution ID",
                        "name": "execution_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.pipelineStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/projects": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    }
                ],
                "description": "Returns all projects for the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "List user projects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.ProjectResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/public/config": {
            "get": {
                "description": "Returns public feature flags such as registration_enabled.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Public runtime config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/syssettings.Settings"
                        }
                    }
                }
            }
        },
        "/api/v1/public/version": {
            "get": {
                "description": "Returns allowlisted product build metadata and Cloud Run identity. This response never includes image digests, environment variables, credentials, project IDs, or user IDs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Build and deployment identity",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/buildinfo.Info"
                        },
                        "headers": {
                            "Cache-Control": {
                                "type": "string",
                                "description": "no-store"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/query": {
            "post": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Full-text search across sources and concepts. Mode \"wiki\" returns raw results, \"full\" adds AI-synthesized answer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search wiki content",
                "parameters": [
                    {
                        "description": "Search query and mode",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.QueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.QueryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ready": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns 200 when the concept cache is warm for the request scope. Returns 503 if the cache is not ready.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ReadyResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handler.ReadyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sources": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns compiled wiki sources plus pending raw rows that have not been compiled.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "List compiled sources and pending raw files",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SourcesListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sources/{id}/annotation": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Get a source annotation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AnnotationResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Save or clear a source annotation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Annotation",
                        "name": "annotation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.AnnotationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AnnotationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "Precondition Failed",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sources/{slug}": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns full content (frontmatter + body) for a wiki source.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Get a source by slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SourceDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/status": {
            "get": {
                "security": [
                    {
                        "DevUserAuth": []
                    },
                    {
                        "ProjectHeader": []
                    }
                ],
                "description": "Returns counts and lock status from GCS, search index, and Firestore.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Pipeline status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/auth.User"
                }
            }
        },
        "auth.LogoutResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "auth.RateLimitErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "retry_after": {
                    "type": "integer"
                }
            }
        },
        "auth.RefreshResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/auth.User"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "default_project_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "auth.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "buildinfo.Info": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "commit": {
                    "type": "string"
                },
                "image_tag": {
                    "type": "string"
                },
                "product_version": {
                    "type": "string"
                },
                "revision": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "gcs.WikiPage": {
            "type": "object",
            "properties": {
                "ann_updated_at": {
                    "type": "string"
                },
                "annotation_allowed": {
                    "type": "boolean"
                },
                "annotation_dirty": {
                    "type": "boolean"
                },
                "concepts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dirty": {
                    "type": "boolean"
                },
                "has_annotation": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "lifecycle_status": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "quality": {
                    "type": "string"
                },
                "raw_dirty": {
                    "type": "boolean"
                },
                "raw_path": {
                    "type": "string"
                },
                "raw_source": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "handler.AnnotationRequest": {
            "type": "object",
            "required": [
                "expected_generation"
            ],
            "properties": {
                "body": {
                    "type": "string"
                },
                "expected_generation": {
                    "type": "string"
                }
            }
        },
        "handler.AnnotationResponse": {
            "type": "object",
            "properties": {
                "ann_sha256": {
                    "type": "string"
                },
                "annotation_dirty": {
                    "type": "boolean"
                },
                "body": {
                    "type": "string"
                },
                "dirty": {
                    "type": "boolean"
                },
                "generation": {
                    "type": "string"
                },
                "has_annotation": {
                    "type": "boolean"
                },
                "lifecycle_status": {
                    "type": "string"
                },
                "raw_dirty": {
                    "type": "boolean"
                },
                "raw_path": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "handler.ConceptDetailResponse": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "frontmatter": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "raw": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handler.ConceptsListResponse": {
            "type": "object",
            "properties": {
                "concepts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gcs.WikiPage"
                    }
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "handler.ImportRequest": {
            "type": "object",
            "required": [
                "urls"
            ],
            "properties": {
                "urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.ImportResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "received": {
                    "type": "integer"
                },
                "urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.PipelineExecutionResponse": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "log_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handler.ProjectResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handler.QueryRequest": {
            "type": "object",
            "properties": {
                "mode": {
                    "type": "string"
                },
                "project": {
                    "type": "string"
                },
                "q": {
                    "type": "string"
                }
            }
        },
        "handler.QueryResponse": {
            "type": "object",
            "properties": {
                "ai_synth": {
                    "type": "string"
                },
                "citations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/search.Citation"
                    }
                },
                "expand": {
                    "$ref": "#/definitions/llm.ExpandResult"
                },
                "mode": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/search.Result"
                    }
                }
            }
        },
        "handler.ReadyResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "prefixes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ready": {
                    "type": "boolean"
                }
            }
        },
        "handler.SourceDetailResponse": {
            "type": "object",
            "properties": {
                "ann_updated_at": {
                    "type": "string"
                },
                "annotation_allowed": {
                    "type": "boolean"
                },
                "annotation_dirty": {
                    "type": "boolean"
                },
                "body": {
                    "type": "string"
                },
                "dirty": {
                    "type": "boolean"
                },
                "frontmatter": {
                    "type": "object",
                    "additionalProperties": true
                },
                "has_annotation": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "lifecycle_status": {
                    "type": "string"
                },
                "raw": {
                    "type": "string"
                },
                "raw_dirty": {
                    "type": "boolean"
                },
                "raw_path": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handler.SourcesListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gcs.WikiPage"
                    }
                }
            }
        },
        "handler.StatusResponse": {
            "type": "object",
            "properties": {
                "concepts_count": {
                    "type": "integer"
                },
                "index_concepts": {
                    "type": "integer"
                },
                "index_sources": {
                    "type": "integer"
                },
                "last_execution": {
                    "$ref": "#/definitions/handler.PipelineExecutionResponse"
                },
                "lock_expiry": {
                    "type": "string"
                },
                "lock_worker": {
                    "type": "string"
                },
                "locked": {
                    "type": "boolean"
                },
                "raw_count": {
                    "type": "integer"
                },
                "running_pipelines": {
                    "type": "integer"
                },
                "sources_count": {
                    "type": "integer"
                }
            }
        },
        "llm.ExpandResult": {
            "type": "object",
            "properties": {
                "additional_request": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "districts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "facilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "suggestions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "pipelinequota.Reason": {
            "type": "string",
            "enum": [
                "",
                "demo",
                "daily_limit",
                "cooldown",
                "already_running",
                "no_new_raw"
            ],
            "x-enum-varnames": [
                "ReasonNone",
                "ReasonDemo",
                "ReasonDailyLimit",
                "ReasonCooldown",
                "ReasonAlreadyRunning",
                "ReasonNoNewRaw"
            ]
        },
        "pipelinequota.Snapshot": {
            "type": "object",
            "properties": {
                "allowed": {
                    "type": "boolean"
                },
                "already_running": {
                    "type": "boolean"
                },
                "annotation_dirty_files": {
                    "type": "integer"
                },
                "cooldown_until": {
                    "type": "string"
                },
                "daily_limit": {
                    "type": "integer"
                },
                "enforced": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "min_new_raw": {
                    "type": "integer"
                },
                "new_raw_files": {
                    "type": "integer"
                },
                "next_reset": {
                    "type": "string"
                },
                "pending_work": {
                    "type": "integer"
                },
                "raw_dirty_files": {
                    "type": "integer"
                },
                "reason": {
                    "$ref": "#/definitions/pipelinequota.Reason"
                },
                "runs_today": {
                    "type": "integer"
                }
            }
        },
        "search.Citation": {
            "type": "object",
            "properties": {
                "path": {
                    "description": "pre-encoded URL path: /concepts/xxx or /sources/xxx",
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "type": {
                    "description": "\"source\" or \"concept\"",
                    "type": "string"
                }
            }
        },
        "search.Result": {
            "type": "object",
            "properties": {
                "slug": {
                    "type": "string"
                },
                "snippet": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "description": "\"source\" or \"concept\"",
                    "type": "string"
                }
            }
        },
        "syssettings.Settings": {
            "type": "object",
            "properties": {
                "registration_enabled": {
                    "type": "boolean"
                }
            }
        },
        "syssettings.patchSettingsRequest": {
            "type": "object",
            "properties": {
                "registration_enabled": {
                    "type": "boolean"
                }
            }
        },
        "v1.pipelineStatusResponse": {
            "type": "object",
            "properties": {
                "last_execution": {
                    "$ref": "#/definitions/handler.PipelineExecutionResponse"
                },
                "project_id": {
                    "type": "string"
                },
                "quota": {
                    "$ref": "#/definitions/pipelinequota.Snapshot"
                },
                "suggested_queries": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Bearer token from /api/v1/auth/login. Format: \\\"Bearer \u003ctoken\u003e\\\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "DevUserAuth": {
            "description": "DEV mode user identity header. Required when dev_jwt=true.",
            "type": "apiKey",
            "name": "X-User-ID",
            "in": "header"
        },
        "ProjectHeader": {
            "description": "Project identifier header.",
            "type": "apiKey",
            "name": "X-Project-ID",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "LLM Wiki BFF API",
	Description:      "Backend-for-frontend API for the LLM Wiki project. Serves wiki sources and concepts with full-text search, import, and pipeline status.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
